mod air_query;
mod analysis;
mod app_controller;
mod arrangement;
mod arrangement_interaction;
mod arrangement_view;
mod artifact_catalog;
mod aspect;
mod asset_view;
mod assets;
mod audio;
mod audio_host;
mod automation;
mod change_set;
mod command;
mod command_journal;
mod command_record;
mod comparison;
mod comparison_runtime;
mod constructive;
mod control_views;
mod coverage;
mod cqt;
mod curve_lang;
mod daw_engine;
mod daw_project;
mod daw_render;
mod decomposition;
#[cfg(test)]
mod engine_regression;
mod explanation;
mod explanation_adapters;
mod export;
mod file_actions;
mod hpss;
mod instruments;
mod interpretation;
mod interpretation_navigation;
mod lens;
mod live_project;
mod loom;
mod media_resolver;
mod mixer;
mod model_claim;
mod model_registry;
mod model_store;
mod model_supervisor;
mod model_task_service;
mod model_wire;
mod model_worker;
mod nmfd;
mod ontology;
mod pattern_actions;
mod pattern_authoring;
mod pattern_lang;
mod persistence;
mod pitch;
mod plugin;
mod project;
mod project_audio_controller;
mod project_codecs;
mod project_controller;
mod project_format;
mod project_io;
mod project_repository;
mod project_selection;
mod project_session;
mod project_store;
mod pyramid;
mod reading;
mod reading_codec;
mod reconstruction;
mod reconstruction_apply;
mod render;
mod render_plan;
mod render_products;
mod render_runtime;
mod render_service;
mod render_validation;
mod rhythm;
mod sample_actions;
mod sample_kit;
mod sample_material;
mod sampler_runtime;
mod sampler_view;
mod sequencer;
mod sequencer_view;
mod session;
mod settings;
mod spectral_tiles;
mod timeline;
mod ui;
mod ui_actions;
mod ui_drag;
mod view_links;
mod waveform_proxy;
mod worker_runtime;
mod workspace;
mod workspace_document;
mod workspace_items;
mod workspace_ui;

use std::path::PathBuf;

use gpui::{App, Application};

fn main() {
    let initial_path = std::env::args_os().nth(1).map(PathBuf::from);

    Application::new().run(move |cx: &mut App| {
        ui::bind_keys(cx);
        arrangement_view::bind_arrangement_keys(cx);
        sequencer_view::bind_keys(cx);
        control_views::bind_control_view_keys(cx);
        ui::init_theme(cx);
        let options = ui::window_options(cx);
        cx.open_window(options, |window, cx| {
            ui::create_workspace(initial_path, window, cx)
        })
        .expect("opening the audec workbench");
        cx.activate(true);
    });
}
