mod air_query;
mod analysis;
mod app_controller;
mod arrangement;
mod arrangement_interaction;
mod arrangement_view;
mod artifact_catalog;
mod artifact_promotion_bridge;
mod aspect;
mod asset_view;
mod assets;
mod audio;
mod audio_host;
mod automation;
mod beat_this;
mod change_set;
mod command;
mod command_journal;
mod command_record;
mod comparison;
mod comparison_controller;
mod comparison_runtime;
mod constructive;
mod control_views;
mod coverage;
mod cqt;
mod curve_lang;
#[cfg(test)]
mod cycle10_acceptance;
#[cfg(test)]
mod cycle9_acceptance;
mod daw_engine;
mod daw_project;
mod daw_render;
mod decomposition;
mod deprojection_evaluation;
mod deprojection_execution;
mod deprojection_program;
#[cfg(test)]
mod engine_regression;
mod explanation;
mod explanation_adapters;
mod explanation_pane_model;
mod explanation_workbench_view;
mod explorer_model;
mod export;
mod file_actions;
mod generative_lowering;
mod generative_ontology;
mod hpss;
mod inference_recipe;
mod instruments;
mod interpretation;
mod interpretation_navigation;
mod lens;
mod live_project;
mod loom;
mod media_resolver;
mod mixer;
mod model_claim;
mod model_registry;
mod model_store;
mod model_supervisor;
mod model_task_service;
mod model_wire;
mod model_worker;
mod nmfd;
mod ontology;
mod pane_audio;
mod pane_session_binding;
mod pattern_actions;
mod pattern_authoring;
mod pattern_controller;
mod pattern_lang;
mod pattern_use_graph;
mod persistence;
mod pitch;
mod plugin;
mod product_action_router;
mod product_input;
mod project;
mod project_audio_controller;
mod project_codecs;
mod project_controller;
mod project_format;
mod project_io;
mod project_repository;
mod project_selection;
mod project_session;
mod project_store;
mod pyramid;
mod reading;
mod reading_codec;
mod reading_query_view;
mod reconstruction;
mod reconstruction_apply;
mod render;
mod render_dependencies;
mod render_dependency_runtime;
mod render_plan;
mod render_products;
mod render_runtime;
mod render_service;
mod render_tiles;
mod render_validation;
mod reverse_navigation;
mod reverse_surface;
mod reverse_surface_view;
mod rhythm;
mod rhythm_explanation;
mod runtime_command_codec;
mod sample_actions;
mod sample_kit;
mod sample_material;
mod sampler_runtime;
mod sampler_view;
mod selection_aspect_service;
mod sequencer;
mod sequencer_view;
mod session;
mod settings;
mod spectral_tiles;
mod timeline;
mod transport_handoff_controller;
mod ui;
mod ui_actions;
mod ui_drag;
mod view_links;
mod waveform_proxy;
mod worker_runtime;
mod workspace;
mod workspace_document;
mod workspace_items;
mod workspace_presenter;
mod workspace_session_layout;
mod workspace_ui;

use std::path::PathBuf;

use gpui::{App, Application};

fn main() {
    let initial_path = std::env::args_os().nth(1).map(PathBuf::from);

    Application::new().run(move |cx: &mut App| {
        ui::bind_keys(cx);
        arrangement_view::bind_arrangement_keys(cx);
        sequencer_view::bind_keys(cx);
        control_views::bind_control_view_keys(cx);
        reading_query_view::bind_reading_query_view_keys(cx);
        ui::init_theme(cx);
        cx.set_menus(ui::app_menus());
        let options = ui::window_options(cx);
        cx.open_window(options, |window, cx| {
            ui::create_workspace(initial_path, window, cx)
        })
        .expect("opening the audec workbench");
        cx.activate(true);
    });
}
